AWSTemplateFormatVersion: '2010-09-09'
Description: Gales Dips Fuel Sales Report Download Service
Parameters:
  IAMUsername:
    Default: sysadmin
    Description: Username of the IAM user for this service
    Type: String
Resources:
  FuelSaleDownloadFunc:
    Properties:
      CodeUri: s3://gales-dips-fuelsale-dwnld/lambda/578ccb628597c6551f6cca7ffaa851e3
      Environment:
        Variables:
          Stage: prod
      Events:
        Create:
          Properties:
            Method: post
            Path: /fuelsale
          Type: Api
        Ping:
          Properties:
            Method: get
            Path: /fuelsale
          Type: Api
      Handler: /fuelsale
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Runtime: go1.x
      Tags:
        BillTo: Gales
      Timeout: 20
    Type: AWS::Serverless::Function
  LambdaExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - logs:*
            Effect: Allow
            Resource: arn:aws:logs:*:*:*
          - Action:
            - dynamodb:DeleteItem
            - dynamodb:DescribeStream
            - dynamodb:GetItem
            - dynamodb:GetRecords
            - dynamodb:GetShardIterator
            - dynamodb:ListStreams
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
            Effect: Allow
            Resource: arn:aws:dynamodb:ca-central-1:407205661819:table/GDS_*
          Version: '2012-10-17'
        PolicyName: root
      - PolicyDocument:
          Statement:
          - Action:
            - ssm:GetParameter*
            Effect: Allow
            Resource:
              Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/prod/gales-dips2*
          Version: '2012-10-17'
        PolicyName: FunctionParameterAccess
      - PolicyDocument:
          Statement:
          - Action:
            - xray:PutTraceSegments
            - xray:PutTelemetryRecords
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: FunctionXRayAccess
      - PolicyDocument:
          Statement:
          - Action:
            - s3:*
            Effect: Allow
            Resource: arn:aws:s3:::gales-dips-fuelsale-dwnld/tankfiles/*
          Version: '2012-10-17'
        PolicyName: FunctionS3Access
    Type: AWS::IAM::Role
Transform: AWS::Serverless-2016-10-31
