AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Gales Dips Fuel Sales Report Download Service

Parameters:
  IAMUsername:
    Description: Username of the IAM user for this service
    Type: String
    Default: sysadmin

Resources:
  FuelSaleDownloadFunc:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      CodeUri: ./dist
      Handler: /fuelsale
      Role: !GetAtt LambdaExecutionRole.Arn

      Timeout: 10
      Environment:
        Variables:
          Stage: prod
      Events:
        Create:
          Type: Api
          Properties:
            Path: /fuelsale
            Method: post
        Ping:
          Type: Api
          Properties:
            Path: /fuelsale
            Method: get
      Tags:
        BillTo: 'Gales'

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: arn:aws:logs:*:*:*
          # - Effect: Allow
          #   Action:
          #   - dynamodb:DeleteItem
          #   - dynamodb:DescribeStream
          #   - dynamodb:GetItem
          #   - dynamodb:GetRecords
          #   - dynamodb:GetShardIterator
          #   - dynamodb:ListStreams
          #   - dynamodb:PutItem
          #   - dynamodb:Query
          #   - dynamodb:Scan
          #   Resource: "arn:aws:dynamodb:ca-central-1:407205661819:table/GDS_*"
      - PolicyName: FunctionParameterAccess
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - ssm:GetParameter*
            - ssm:GetParametersByPath
            Resource:
              Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/prod/gdps-fs-dwnld*
      - PolicyName: FunctionXRayAccess
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - xray:PutTraceSegments
            - xray:PutTelemetryRecords
            Resource: '*'
      - PolicyName: FunctionS3Access
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:*
            Resource: arn:aws:s3:::gdps-fs-dwnld/reports/*
